apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  labels:
    app: operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operator
  template:
    metadata:
      labels:
        app: operator
    spec:
      serviceAccountName: my-serviceaccount
      containers:
      - name: busybox
        image: busybox
        command:
          - sleep
          - "3600"
---
apiVersion: v1
kind: Service
metadata:
  name: operator
  labels:
    app: operator
spec:
  selector:
    app: operator
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
